# Generated by Django 3.1.3 on 2021-03-09 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arboles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbol',
            name='cuidado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arboles_cuidados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arbol',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arboles.arbolespecie'),
        ),
        migrations.AddField(
            model_name='arbol',
            name='plantado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arboles_plantados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arbol',
            name='siembra_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arboles.arbolestado'),
        ),
        migrations.AddField(
            model_name='arbol',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arboles.arbolubicacion'),
        ),
    ]
